### ISSUE TITLE
[5월 1일-5월 2일] 황지수 TODO

### ISSUE THREAD

**Issue by JiSoo-Hwang** [JiSoo-Hwang/PJT_GBangE#3]
5월 1일(1일차)
- [ ] github push/pull request 제대로 숙지하기
- [ ] TRAINING(러닝일지) 테이블 생성 및 VO 완성하기
- [ ] TRAINING_CATEGORY (훈련종류) 테이블 생성 및 VO완성하기
- [ ] SHOES 테이블 생성 및 VO 완성하기
- [ ] 호연님이 제공해주신 홈페이지 참조하여 게시판 레이아웃 만들기(함께 논의 후 제작)

5월 2일(2일차)
- [ ] 게시판 레이아웃 만들기 마무리
- [ ] 다른 분들이 만드신 테이블 생성하기
- [ ] 게시글 작성 테스트를 위해선 회원 정보가 있어야 하니 로컬 MEMBER테이블에 admin과 user01-user05까지 유저 정보를 추가하기
- [ ] 오늘은 CRUD 중에서 'C'를 기능 만들기 (게시글 작성)

5월 3일(3일차)
- [ ] 오늘은 CRUD 중에서 'R'기능 만들기(게시글 조회)
- [ ] 게시글 조회 기능을 만들려면 목록 페이지가 있어야 하니 목록 페이지도 만들기
