### ISSUE TITLE
[5월 1일 - 5월 2일] 신호연 TODO

### ISSUE THREAD

**Issue by ho4179** [JiSoo-Hwang/PJT_GBangE#4]
5월 1일(1일차)
- [ ] github push/pull request 제대로 숙지하기
- [ ] NOTICE 테이블 생성 및 VO 완성하기
- [ ] 준형님이 주신 NAVI바 적용하기
- [ ] NOTICE 게시판 레이아웃 틀 잡기

5월 2일(2일차)
- [ ] 게시판 레이아웃 만들기 마무리
- [ ] 다른 분들이 만드신 테이블 생성하기
